name: Audit

on:
  schedule:
    - cron: 56 11 * * WED

jobs:
  pnpm-audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: 23.x
          cache: pnpm

      - run: pnpm audit
