name: Release

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      pages: write

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: 23.x
          registry-url: https://registry.npmjs.org
          cache: pnpm

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Build
        run: |
          pnpm install
          pnpm run docs

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./docs-dist/"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Send ping to blogmura
        run: "curl ${{ secrets.BLOGMURA_PING_URL }}"
